### ISSUE TITLE
TypeError: _this._afterConnect is not a function

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/grow.js#62]
Line 87 

`this._afterConnect(callback, result);
`

When running `light.js` from Grow-Iot Quickstart, this line causes this error

```
Grow server connection established.
/home/cloud/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469
          _this._afterConnect(callback, result);
                ^

TypeError: _this._afterConnect is not a function
    at /home/cloud/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469:17
    at self._callbacks.(anonymous function) (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:434:16)
    at DDPClient._message (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:156:7)
    at null.<anonymous> (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:96:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at EventTarget.dispatchEvent (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at instance._receiveMessage (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at null.<anonymous> (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:82:20)
```

**Comment by JakeHartnell** [comment]
https://github.com/CommonGarden/Grow-IoT/issues/163

**Comment by JakeHartnell** [comment]
Is anyone else having this problem? I'm having trouble reproducing this...

**Comment by JakeHartnell** [comment]
http://www.darul.io/post/2016-01-07_what-is-babel-js-doing

**Comment by JakeHartnell** [comment]
The code is not being compiled to ES2015 correctly... should resolve this soon.
