### ISSUE TITLE
Not working on Tessel 2

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/grow.js#64]
```
/tmp/remote-script/node_modules/Grow.js/dist/Grow.umd.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):t.Grow=e()}(this,function(){"use strict";var r,e,i,h,b,c,f,p,t,a,k,o,u,l,d,m,g,y,s,n={};return n.typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol?"symbol":typeof e},n.classCallCheck=function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")},n.createClass=function(){function e(n,r){var t,e;for(t=0;t<r.length;t++)e=r[t],e.enumerable=e.enumerable||!1,e.configurable=!0,"value"in e&&(e.writable=!0),Object.defineProperty(n,e.key,e)}return function(t,r,n){return r&&e(t.prototype,r),n&&e(t,n),t}}(),r={},r.classCallCheck=function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")},r.

TypeError: r._afterConnect is not a function
    at /tmp/remote-script/node_modules/Grow.js/dist/Grow.umd.js:1:5235
    at e._callbacks.(anonymous function) (/tmp/remote-script/node_modules/ddp/lib/ddp-client.js:1:6236)
    at e._message (/tmp/remote-script/node_modules/ddp/lib/ddp-client.js:1:2570)
    at null.<anonymous> (/tmp/remote-script/node_modules/ddp/lib/ddp-client.js:1:1715)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at n.dispatchEvent (/tmp/remote-script/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:1:375)
    at t._receiveMessage (/tmp/remote-script/node_modules/faye-websocket/lib/faye/websocket/api.js:1:2612)
    at null.<anonymous> (/tmp/remote-script/node_modules/faye-websocket/lib/faye/websocket/api.js:1:744)
    at emitOne (events.js:82:20)

```

**Comment by JakeHartnell** [comment]
Duplicate of #62?
