### ISSUE TITLE
  TypeError: Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/grow.js#65]
The Quickstart guide directions no longer allow devices to connect to the Grow-IoT process.

 Error code following: 

```
/home/josh/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:403
        this.uuid = this.thing.uuid || null;
                              ^

TypeError: Cannot read property 'uuid' of undefined
    at new Grow (/home/josh/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:403:31)
    at Object.<anonymous> (/home/josh/my-plant-light/light.js:6:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by JakeHartnell** [comment]
Should be fixed with Grow.js v0.2.5
